# Naive Bayes
Naive Bayes methods are a set of supervised learning algorithms based on applying Bayes’ theorem with the “naive” assumption of conditional independence between every pair of features given the value of the class variable (for more information visit this link: [Naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html))

$$ \begin{aligned}
p(Y \mid X_1, \ldots, X_p) & = \frac{ p(Y) p( X_1, \ldots, X_p \mid Y) }{ p( X_1, \ldots, X_p) }\\
\approx p(Y) \prod_{i=1}^p p(X_i \mid Y)
\end{aligned}$$

In [73]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix, precision_score, classification_report

In [82]:
df = pd.read_csv('./data/mushrooms.csv')
df.head(4)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  

[4 rows x 23 columns]

### Gaussian Naive Bayes
For this approach I use two methods to convert categorical variables to numerical variables.
- LabelEncoder
- OneHotEncoder

In [79]:
model = GaussianNB()

y = df['class'].apply(lambda x:1 if x=='e' else 0).values
df.drop('class', axis=1, inplace=True)

x = df.apply(preprocessing.LabelEncoder().fit_transform)

x.head(4)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=50)

y_pred = model.fit(x_train, y_train).predict(x_test)

print(f'The precision score is: {precision_score(y_test, y_pred)}')

print(f'The confusion matrix is:\n\n{confusion_matrix(y_test, y_pred)}')

The precision score is: 0.9039408866995073
The confusion matrix is:

[[744  78]
 [ 69 734]]


In [80]:
x = OneHotEncoder().fit_transform(df)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=50)

model = BernoulliNB()

y_pred = model.fit(x_train, y_train).predict(x_test)

print(f'The precision score is: {precision_score(y_test, y_pred)}')

print(f'The confusion matrix is:\n\n{confusion_matrix(y_test, y_pred)}')

The precision score is: 0.8885135135135135
The confusion matrix is:

[[723  99]
 [ 14 789]]


## Bernoulli Naive Bayes

In [83]:
model = BernoulliNB()

y = df['class'].apply(lambda x:1 if x=='e' else 0).values
df.drop('class', axis=1, inplace=True)

x = df.apply(preprocessing.LabelEncoder().fit_transform)

x.head(4)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=50)

y_pred = model.fit(x_train, y_train).predict(x_test)

print(f'The precision score is: {precision_score(y_test, y_pred)}')

print(f'The confusion matrix is:\n\n{confusion_matrix(y_test, y_pred)}')

The precision score is: 0.7614770459081837
The confusion matrix is:

[[583 239]
 [ 40 763]]


In [84]:
x = OneHotEncoder().fit_transform(df)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=50)

model = BernoulliNB()

y_pred = model.fit(x_train, y_train).predict(x_test)

print(f'The precision score is: {precision_score(y_test, y_pred)}')

print(f'The confusion matrix is:\n\n{confusion_matrix(y_test, y_pred)}')

The precision score is: 0.8885135135135135
The confusion matrix is:

[[723  99]
 [ 14 789]]
